name: 1 - test mock back

on:
  push:
    branches: ["1-mock-livres"]

defaults:
  run:
    working-directory: backend

jobs:
  test:
    name: ğŸª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ¤© Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ§ª Installation des dependances
        run: npm install

      - name: ğŸ˜ Lancement des tests backend
        run: npm run test:ci
