name: 1 - test mock back

on:
  push:
    branches: ["1-mock-livres"]

jobs:
  test:
    name: ğŸª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ¤© Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ§ª Installation des dependances
        run: |
          cd backend
          npm install
